[package]
name = "rr_rustc_interface"
authors = ["The RefinedRust Developers and Contributors"]
license = "BSD-3-Clause"

edition.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
