Section resolve_ghost.
  Context {T_rt : Type}.
  Context (T_ty : type (T_rt)).

  (* NOTE Resolution of ghost variables over the invariant -- not currently automatically generated by the frontend. *)
  Lemma resolve_ghost_Vec_T π E L rm l rs T :
    (∀ li, resolve_ghost_iter π E L rm false li (ty_syn_type T_ty) (replicate (length rs) (◁ T_ty))%I (Owned false) rs [] 0%nat (λ L2 rs' R progress,
      T L2 (#rs') R progress)) ⊢
    resolve_ghost π E L rm true l (◁ Vec_inv_t T_ty) (Owned false) (#rs) T.
  Proof.
  Admitted.
  Global Instance resolve_ghost_Vec_T_inst π E L rm l rs : ResolveGhost π E L rm true l (◁ Vec_inv_t T_ty)%I (Owned false) (#rs) :=
    λ T, i2p (resolve_ghost_Vec_T π E L rm l rs T).
End resolve_ghost.
