[package]
name = "analysis_driver"
edition = "2021"
version = "1.0.0"
authors = ["Federico Poli <federpoli@gmail.com>"]
license = "MPL-2.0"

[dependencies]
analysis.path = "../.."
rr_rustc_interface.path = "../../../rr_rustc_interface"

env_logger = "0.11"
serde_json = "1"

[workspace]
