absolute-paths-allowed-crates = [
  "hir",
  "polonius_engine",
  "radium",
  "rrconfig",
  "rustc_abi",
  "rustc_ast",
  "rustc_ast",
  "rustc_attr",
  "rustc_borrowck",
  "rustc_borrowck",
  "rustc_data_structures",
  "rustc_driver",
  "rustc_errors",
  "rustc_hir",
  "rustc_index",
  "rustc_infer",
  "rustc_interface",
  "rustc_middle",
  "rustc_session",
  "rustc_span",
  "rustc_target",
  "rustc_trait_selection",
  "rustc_type_ir",
  "serde_json"
]

avoid-breaking-exported-api = false
