(* NOTE: variance proofs are currently not automatically generated by the frontend *)
Lemma Option_ty_weak_subtype E L {T_rt1 T_rt2} (T_ty1 : type T_rt1) (T_ty2 : type T_rt2) r1 r2 T :
  (∃ r2', ⌜ r2 = Some (#r2')⌝ ∗ weak_subtype E L r1 r2' T_ty1 T_ty2 T) ⊢
  weak_subtype E L (Some (#r1)) r2 (Option_ty T_ty1) (Option_ty T_ty2) T.
Proof.
Admitted.
Global Instance Option_ty_weak_subtype_inst E L {T_rt1 T_rt2} (T_ty1 : type T_rt1) (T_ty2 : type T_rt2) r1 r2 :
Subtype E L (Some (#r1)) r2 (Option_ty T_ty1) (Option_ty T_ty2) := λ T, i2p (Option_ty_weak_subtype E L T_ty1 T_ty2 r1 r2 T).
